package reattribute

import (
	"context"
	"fmt"
	"os"
	"testing"
)

// TestRun_FileSubsetAcceptsBigintFileIDs pins the cast fix that followed the
// media_files.id widening: every $2 parameter in the
// file-subset path is bound as bigint[], so a moved file id above 2^31 no
// longer raises "integer out of range" before the first UPDATE runs.
//
// The per-file child columns (admin_playback_history.media_file_id,
// user_downloads.media_file_id, downloads.media_file_id,
// user_watch_progress.last_file_id) are still integer on purpose, so no child
// row can carry the wide id yet. The test therefore moves one wide file (a
// real media_files row, no children) together with one int4-range file that
// does own state, and checks that the run succeeds and the int4 rows still
// move: integer = ANY(bigint[]) compares correctly in both directions.
func TestRun_FileSubsetAcceptsBigintFileIDs(t *testing.T) {
	dsn := os.Getenv("SILO_TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("SILO_TEST_DATABASE_URL is not set")
	}
	ctx := t.Context()

	env := newTestEnv(t)
	from := fmt.Sprintf("movie-src-%d", env.suffix)
	to := fmt.Sprintf("movie-dst-%d", env.suffix)

	// A runtime variable rather than a constant so the int conversion below
	// is not rejected at compile time on a 32-bit GOARCH.
	var wideFileID int64 = 3_000_000_000
	var folderID int
	if err := env.pool.QueryRow(ctx,
		`INSERT INTO media_folders (type, name, enabled) VALUES ('movies', $1, true) RETURNING id`,
		fmt.Sprintf("reattr-bigint-folder-%d", env.suffix),
	).Scan(&folderID); err != nil {
		t.Fatalf("seed folder: %v", err)
	}
	// The identity column is GENERATED BY DEFAULT, so an explicit id is
	// accepted without OVERRIDING SYSTEM VALUE.
	if _, err := env.pool.Exec(ctx, `
		INSERT INTO media_files (id, content_id, media_folder_id, file_path, file_size)
		VALUES ($1, $2, $3, $4, 1000)
	`, wideFileID, from, folderID, fmt.Sprintf("/reattr-bigint/%d/wide.mkv", env.suffix)); err != nil {
		t.Fatalf("seed wide media file: %v", err)
	}
	t.Cleanup(func() {
		if _, err := env.pool.Exec(context.Background(), `DELETE FROM media_files WHERE id = $1`, wideFileID); err != nil {
			t.Errorf("cleanup file: %v", err)
		}
		if _, err := env.pool.Exec(context.Background(), `DELETE FROM media_folders WHERE id = $1`, folderID); err != nil {
			t.Errorf("cleanup folder: %v", err)
		}
	})

	movedFile, stayFile := 950001, 950002
	for i, fileID := range []int{movedFile, stayFile} {
		if _, err := env.pool.Exec(ctx, `
			INSERT INTO admin_playback_history (session_id, user_id, profile_id, media_item_id, media_file_id, play_method, started_at, ended_at)
			VALUES ($1, $2, $3, $4, $5, 'direct', now(), now())
		`, fmt.Sprintf("sess-bigint-%d-%d", env.suffix, i), env.userID, env.profileID, from, fileID); err != nil {
			t.Fatalf("seed session: %v", err)
		}
	}
	if _, err := env.pool.Exec(ctx, `
		INSERT INTO user_downloads (id, user_id, profile_id, media_item_id, media_file_id)
		VALUES ($1, $2, $3, $4, $5)
	`, fmt.Sprintf("dl-bigint-%d", env.suffix), env.userID, env.profileID, from, movedFile); err != nil {
		t.Fatalf("seed download: %v", err)
	}
	if _, err := env.pool.Exec(ctx, `
		INSERT INTO user_watch_progress (user_id, profile_id, media_item_id, position_seconds, duration_seconds, last_file_id)
		VALUES ($1, $2, $3, 100, 7200, $4)
	`, env.userID, env.profileID, from, movedFile); err != nil {
		t.Fatalf("seed progress: %v", err)
	}

	// Evidence mode walks every $2::bigint[] site: the three exact-table
	// updates, the three progress statements, and the evidence CTE (both in
	// the history update and in the classification tally).
	report := env.run(t, Options{
		FromContentID: from,
		ToContentID:   to,
		MovedFileIDs:  []int{int(wideFileID), movedFile},
		Mode:          HistoryModeEvidence,
	})

	if report.PlaybackSessionLog != 1 || report.Downloads != 1 || report.ProgressMoved != 1 {
		t.Fatalf("report = %+v, want 1 session log, 1 download, 1 progress moved", report)
	}
	if got := env.itemIDOf(t, "admin_playback_history", "user_id = $1 AND media_file_id = $2", env.userID, movedFile); got != to {
		t.Fatalf("moved session item = %q, want %q", got, to)
	}
	if got := env.itemIDOf(t, "admin_playback_history", "user_id = $1 AND media_file_id = $2", env.userID, stayFile); got != from {
		t.Fatalf("stayed session item = %q, want %q", got, from)
	}
	if got := env.itemIDOf(t, "user_downloads", "user_id = $1", env.userID); got != to {
		t.Fatalf("download item = %q, want %q", got, to)
	}
	if got := env.itemIDOf(t, "user_watch_progress", "user_id = $1", env.userID); got != to {
		t.Fatalf("progress item = %q, want %q", got, to)
	}
}
