import {
  Bell,
  Captions,
  Database,
  Download,
  Library,
  Paintbrush,
  PlayCircle,
  Plug,
  RefreshCw,
  Settings2,
  Sparkles,
  Users,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

import type { SettingsSearchGroup, SettingsSearchItem } from "@/components/settings/settingsSearch";

export interface AdminSettingsSearchItem extends SettingsSearchItem {
  id: string;
  label: string;
  description: string;
  /** The named sections visible inside this settings destination. */
  groups: readonly string[];
  keywords?: readonly string[];
  settings?: readonly { label: string; description?: string; keywords?: readonly string[] }[];
  icon: LucideIcon;
  /**
   * Short qualifier rendered next to the label in a nav that wants one. The
   * settings rail reads section health as a status dot instead, so nothing
   * sets this today; the prop stays so a future nav can opt in without
   * reshaping the item type.
   */
  badge?: string;
}

export type AdminSettingsSearchGroup = SettingsSearchGroup<AdminSettingsSearchItem>;

const settingIndex = (...labels: string[]) => labels.map((label) => ({ label }));

// Page ids are stable route segments. Old ids from the 20-tab layout are kept
// working by LEGACY_ADMIN_SETTINGS_PAGE_ALIASES below — regroup or reorder
// freely, but add an alias entry whenever an id disappears.
//
// One group keeps the Overview cards and command palette in the same order.
export const ADMIN_SETTINGS_GROUPS: AdminSettingsSearchGroup[] = [
  {
    label: "Settings",
    items: [
      {
        id: "general",
        label: "General",
        description: "Server identity, public signups, and logging.",
        groups: ["Identity", "Access", "Logging"],
        keywords: [
          "server name",
          "login subtitle",
          "signup",
          "invite",
          "log level",
          "quiet",
          "silenced log messages",
          "branding name",
        ],
        settings: settingIndex(
          "Identity",
          "Server name",
          "Login subtitle",
          "Access",
          "Public signups",
          "Logging",
          "Log level",
          "Quiet log prefixes",
        ),
        icon: Settings2,
      },
      {
        id: "infrastructure",
        label: "Storage & Database",
        description: "Redis, S3 storage buckets, the database, and log retention.",
        groups: ["Redis", "Public storage", "Private storage", "Database", "Logs"],
        keywords: [
          "redis",
          "s3",
          "bucket",
          "endpoint",
          "region",
          "access key",
          "secret key",
          "postgres",
          "pool",
          "user db",
          "ops log",
          "retention",
          "decision log",
          "opa",
          "infrastructure",
        ],
        settings: settingIndex(
          "Redis",
          "Use Redis",
          "Connection URL",
          "Public storage",
          "Private storage",
          "Endpoint",
          "Region",
          "Bucket",
          "Access Key",
          "Secret Key",
          "Put the bucket name in the URL path",
          "Folder inside the bucket",
          "How asset links are authorized",
          "Address clients download from",
          "Token Secret",
          "Token query parameter",
          "Link lifetime (seconds)",
          "Database",
          "Maximum Postgres connections",
          "Where per-user data is stored",
          "Open files per user",
          "Close idle user databases after",
          "Logs",
          "How much to record",
          "Delete log entries older than (days)",
          "Maximum log entries",
          "Maximum log size (MB)",
          "Delete permission records older than (days)",
          "Record one allowed check in every",
        ),
        icon: Database,
      },
      {
        id: "appearance",
        label: "Appearance",
        description: "Logos, accent color, default theme, custom CSS, and poster badges.",
        groups: ["Logos and icons", "Colors and theme", "Card overlays"],
        keywords: [
          "logo",
          "wordmark",
          "favicon",
          "login background",
          "white label",
          "brand",
          "accent color",
          "default theme",
          "app name",
          "pwa",
          "light theme logo",
          "light wordmark",
          "light icon",
          "theme",
          "custom css",
          "community themes",
          "overlays",
          "poster badges",
        ],
        settings: settingIndex(
          "Logos and icons",
          "Logo (wordmark)",
          "Logo (wordmark, light themes)",
          "Logo (icon)",
          "Logo (icon, light themes)",
          "Favicon",
          "Login background",
          "Colors and theme",
          "Accent color",
          "Custom accent color",
          "Default theme",
          "Individual colors and fonts",
          "Custom CSS",
          "Community theme list",
          "Card overlays",
          "Show badges on poster art",
          "Badge style",
        ),
        icon: Paintbrush,
      },
      {
        id: "security",
        label: "Security & Access",
        description: "Sign-in sessions, trusted proxies, and request rate limits.",
        groups: ["Sign-in sessions", "Network", "Rate limiting"],
        keywords: [
          "access token",
          "refresh token",
          "expiry",
          "session",
          "proxy",
          "x-forwarded-for",
          "client ip",
          "rate limit",
          "throttle",
          "429",
          "api key tier",
          "security",
        ],
        settings: settingIndex(
          "Sign-in sessions",
          "Access token expiry",
          "Refresh token expiry",
          "Network",
          "Trusted proxies",
          "Rate limiting",
          "Enable rate limiting",
          "Where counters are kept",
          "Whole-server requests per second",
          "Per client address",
          "Burst allowance",
          "Standard API keys",
          "Elevated API keys",
        ),
        icon: Users,
      },
      {
        id: "library",
        label: "Library & Metadata",
        description: "Artwork storage, scanning, intro and credits markers, and catalog search.",
        groups: ["Artwork", "Scanning", "Intro and credits markers", "Search"],
        keywords: [
          "scanner workers",
          "matcher",
          "batch size",
          "artwork",
          "posters",
          "image caching",
          "cache images",
          "object storage",
          "intro",
          "credits",
          "recap",
          "markers",
          "marker detection",
          "meilisearch",
          "postgres search",
          "semantic",
          "metadata",
        ],
        settings: settingIndex(
          "Artwork",
          "Store artwork in your bucket",
          "Scanning",
          "Scanner workers",
          "Matcher workers",
          "Matcher batch size",
          "Intro and credits markers",
          "Find intros and credits",
          "Fetch markers on playback",
          "Populate markers",
          "Contribute markers",
          "Search",
          "Search engine",
          "Meilisearch URL",
          "Meilisearch API key",
          "Index name prefix",
          "Query timeout (ms)",
          "When a search has several words",
          "Items sent to the index per batch",
          "Match by meaning as well as words",
          "Meaning-based share of results",
          "Search status",
        ),
        icon: Library,
      },
      {
        id: "playback",
        label: "Playback",
        description: "Transcoding, hardware acceleration, and watch thresholds.",
        groups: ["Transcoding", "Watch behavior"],
        keywords: [
          "ffmpeg",
          "transcode",
          "hardware acceleration",
          "gpu",
          "chapter thumbnails",
          "watched threshold",
          "resume",
          "4k",
        ],
        settings: settingIndex(
          "Transcoding",
          "Hardware acceleration",
          "Allow 4K transcoding",
          "FFmpeg path",
          "Transcode directory",
          "GPU devices",
          "Local transcode fallback",
          "Throttle transcoding",
          "Buffer ahead (seconds)",
          "Chapter thumbnail workers",
          "Generate chapter thumbnails on",
          "HDR handling",
          "Convert HDR colors on the CPU when the GPU cannot",
          "Watch behavior",
          "Mark watched at (%)",
          "Show in Continue Watching after (%)",
        ),
        icon: PlayCircle,
      },
      {
        id: "downloads",
        label: "Downloads",
        description: "Offline downloads, per-user and server-wide limits, and prepared copies.",
        groups: ["Downloads"],
        keywords: [
          "downloads",
          "offline",
          "bandwidth",
          "mbps",
          "throttle",
          "quota",
          "concurrency",
          "prepared copies",
          "artifacts",
          "storage budget",
        ],
        settings: settingIndex(
          "Downloads",
          "Allow downloads",
          "Per-user bandwidth",
          "Per user",
          "Downloads at once per user",
          "Downloads per period",
          "Period length",
          "Whole server",
          "Server bandwidth",
          "Prepare device-friendly copies",
          "Prepared file directory",
          "Files prepared at once",
          "Prepared file storage budget",
        ),
        icon: Download,
      },
      {
        id: "providers",
        label: "Subtitles & Metadata",
        description: "Subtitle provider accounts, the MDBList metadata key, and marker providers.",
        groups: ["Subtitle providers", "Metadata providers", "Marker providers"],
        keywords: [
          "opensubtitles",
          "subdl",
          "subsource",
          "mdblist",
          "subtitles",
          "captions",
          "api key",
          "provider credentials",
          "integrations",
          "theintrodb",
          "introdb",
          "marker providers",
          "markers",
          "intro",
          "credits",
        ],
        settings: settingIndex(
          "Subtitle providers",
          "OpenSubtitles",
          "SubDL",
          "SubSource",
          "Username",
          "Password",
          "API key",
          "Metadata providers",
          "MDBList",
          "Marker providers",
          "TheIntroDB",
          "Use for online marker lookup",
          "Lookup order",
          "Allow contributions",
          "Send this server's markers automatically",
          "Minimum confidence",
        ),
        icon: Captions,
      },
      {
        id: "watch-sync",
        label: "Watch Providers",
        description:
          "Trakt, Simkl, and watch-provider plugins that profiles connect their own accounts to.",
        groups: ["Watch providers"],
        keywords: [
          "trakt",
          "simkl",
          "scrobble",
          "watch providers",
          "client id",
          "client secret",
          "sync",
          "integrations",
          "plugin",
        ],
        settings: settingIndex("Watch providers", "Trakt", "Simkl", "Client ID", "Client secret"),
        icon: RefreshCw,
      },
      {
        id: "ai",
        label: "AI Services",
        description: "Text and speech-to-text models, and the features that spend them.",
        groups: ["Models", "Features", "Usage and tuning"],
        keywords: [
          "openai",
          "ollama",
          "groq",
          "whisper",
          "llm",
          "model",
          "translation",
          "transcription",
          "subtitle translation",
          "integrations",
        ],
        settings: settingIndex(
          "Models",
          "Text model",
          "Speech-to-text",
          "Base URL",
          "Model",
          "API key",
          "Features",
          "Translate subtitles",
          "Create subtitles from audio",
          "Translate descriptions",
          "Description translation for viewers",
          "Jobs running at once",
          "Subtitle lines per request",
          "Surrounding lines sent for context",
          "Audio sent per request (seconds)",
          "Transcriptions per account",
          "Allowance resets",
        ),
        icon: Sparkles,
      },
      {
        id: "notifications",
        label: "Notifications",
        description: "Release events, delivery channels, the mail server, and webhooks.",
        groups: ["Release events", "Delivery channels", "Tuning", "Retention"],
        keywords: [
          "release events",
          "new episode",
          "email",
          "smtp",
          "mail",
          "silo push relay",
          "mobile push",
          "apns",
          "fcm",
          "discord",
          "web push",
          "webhooks",
          "server channels",
          "digest",
        ],
        settings: settingIndex(
          "Notice new content",
          "Enable release events",
          "Work out who wants it",
          "Enable fanout",
          "Delivery Channels",
          "In-App",
          "Web Push",
          "Silo Push Relay",
          "Relay URL",
          "Deployment ID",
          "Apple Push (APNs)",
          "Android Push (FCM)",
          "Email",
          "Send email from this server",
          "From address",
          "From name",
          "Mail server address",
          "Port",
          "Encryption",
          "Username",
          "Password",
          "Test email recipient",
          "Let people pick an email per episode",
          "Send the daily summary at",
          "Link back to this server at",
          "Discord",
          "Client ID",
          "Client secret",
          "Bot token",
          "Let people pick a DM per episode",
          "Show artwork in Discord messages",
          "Mention the requester on Discord",
          "Personal Webhooks",
          "Webhooks each person may create",
          "Webhook calls per minute, per person",
          "Allow webhooks to private addresses",
          "Server Channels",
          "Collect new items for (seconds)",
          "Grouping and flood control",
          "Wait before sending (seconds)",
          "Most messages per show at once",
          "Give up on content older than (hours)",
          "How long notifications are kept",
        ),
        icon: Bell,
      },
      {
        id: "compatibility",
        label: "Compatibility",
        description:
          "Jellyfin and Audiobookshelf client compatibility and the Jellyfin web player.",
        groups: ["Jellyfin", "Audiobookshelf"],
        keywords: [
          "jellyfin",
          "audiobookshelf",
          "abs",
          "proxy",
          "public url",
          "server id",
          "session ttl",
          "web player",
        ],
        settings: settingIndex(
          "Jellyfin",
          "Allow Jellyfin apps to connect",
          "Address Jellyfin apps should use",
          "Jellyfin Web install progress",
          "Web player version to install",
          "Web player install folder",
          "Name shown to Jellyfin apps",
          "Server ID",
          "Jellyfin version to report",
          "Stay signed in for",
          "Forget idle playback after",
          "Audiobookshelf",
          "Allow Audiobookshelf apps to connect",
        ),
        icon: Plug,
      },
    ],
  },
];

export const ADMIN_SETTINGS_NAV = ADMIN_SETTINGS_GROUPS.flatMap((group) => group.items);

const ADMIN_SETTINGS_PAGE_IDS = new Set(ADMIN_SETTINGS_NAV.map((item) => item.id));

/**
 * Deep links from earlier layouts. Bookmarks, docs, and older client builds
 * still point at these ids, so every one of them resolves to the page that
 * absorbed it rather than falling through to the settings overview.
 */
export const LEGACY_ADMIN_SETTINGS_PAGE_ALIASES: Readonly<Record<string, string>> = {
  branding: "appearance",
  theming: "appearance",
  overlays: "appearance",
  "rate-limiting": "security",
  scanner: "library",
  search: "library",
  intro: "library",
  subtitles: "providers",
  integrations: "providers",
  "watch-providers": "watch-sync",
  email: "notifications",
  jellyfin: "compatibility",
  "compatibility-proxies": "compatibility",
  database: "infrastructure",
  storage: "infrastructure",
  "log-retention": "infrastructure",
};

/** Resolves a route segment or legacy `?tab=` value to a current page id. */
export function resolveAdminSettingsPageID(value: string | null): string | null {
  if (!value) return null;
  if (ADMIN_SETTINGS_PAGE_IDS.has(value)) return value;
  return LEGACY_ADMIN_SETTINGS_PAGE_ALIASES[value] ?? null;
}
