package migrations

import (
	"fmt"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
)

const widenCoreIDsMigrationName = "20260912231715_widen_core_ids_to_bigint"

var coreIDParents = []string{"media_folders", "users", "media_files"}

func coreIDFixture(t *testing.T) (pgx.Tx, string) {
	t.Helper()
	tx, schema := adminMigrationFixture(t)
	for _, table := range coreIDParents {
		migrationExec(t, tx, fmt.Sprintf(`CREATE TABLE %s (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL DEFAULT 'fixture');
CREATE TABLE %s_children (id integer REFERENCES %s(id), wide_id bigint REFERENCES %s(id));
CREATE INDEX ON %s_children(id); CREATE INDEX ON %s_children(wide_id);
INSERT INTO %s(name) VALUES ('existing'); INSERT INTO %s_children VALUES (1,1);`, table, table, table, table, table, table, table, table))
	}
	return tx, schema
}

func assertCoreIDTypes(t *testing.T, tx pgx.Tx, schema, want string) {
	t.Helper()
	for _, table := range coreIDParents {
		var column, sequence string
		var child string
		err := tx.QueryRow(t.Context(), `SELECT a.atttypid::regtype::text, s.seqtypid::regtype::text,
    (SELECT atttypid::regtype::text FROM pg_attribute WHERE attrelid=$2::regclass AND attname='id')
FROM pg_attribute a JOIN pg_sequence s ON s.seqrelid=pg_get_serial_sequence($1,'id')::regclass
WHERE a.attrelid=$1::regclass AND a.attname='id'`, schema+"."+table, schema+"."+table+"_children").Scan(&column, &sequence, &child)
		if err != nil {
			t.Fatal(err)
		}
		if column != want || sequence != want || child != "integer" {
			t.Fatalf("%s column/sequence/child = %s/%s/%s", table, column, sequence, child)
		}
	}
	var invalid int
	if err := tx.QueryRow(t.Context(), `SELECT (SELECT count(*) FROM pg_constraint WHERE connamespace=$1::regnamespace AND NOT convalidated) + (SELECT count(*) FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid WHERE c.relnamespace=$1::regnamespace AND NOT indisvalid)`, schema).Scan(&invalid); err != nil {
		t.Fatal(err)
	}
	if invalid != 0 {
		t.Fatalf("%d invalid constraints/indexes", invalid)
	}
}

func TestWidenCoreIDsPostgresRoundTrip(t *testing.T) {
	tx, schema := coreIDFixture(t)
	up := adminMigrationSQL(t, widenCoreIDsMigrationName, schema, false)
	down := adminMigrationSQL(t, widenCoreIDsMigrationName, schema, true)
	migrationExec(t, tx, up)
	migrationExec(t, tx, up) // Retry after a completed apply preserves data and sequence state.
	assertCoreIDTypes(t, tx, schema, "bigint")
	for _, table := range coreIDParents {
		var next int64
		if err := tx.QueryRow(t.Context(), "INSERT INTO "+table+" DEFAULT VALUES RETURNING id").Scan(&next); err != nil {
			t.Fatal(err)
		}
		if next != 2 {
			t.Fatalf("%s next id=%d, want 2", table, next)
		}
		migrationExec(t, tx, fmt.Sprintf("INSERT INTO %s(id) VALUES (3000000000); INSERT INTO %s_children(wide_id) VALUES(3000000000)", table, table))
		requireMigrationSQLState(t, tx, fmt.Sprintf("INSERT INTO %s_children(id) VALUES(3000000000)", table), "22003")
		migrationExec(t, tx, fmt.Sprintf("DELETE FROM %s_children WHERE wide_id=3000000000; DELETE FROM %s WHERE id=3000000000", table, table))
	}
	migrationExec(t, tx, down)
	assertCoreIDTypes(t, tx, schema, "integer")
	migrationExec(t, tx, up)
	assertCoreIDTypes(t, tx, schema, "bigint")
	for _, table := range coreIDParents {
		var next int64
		if err := tx.QueryRow(t.Context(), "INSERT INTO "+table+" DEFAULT VALUES RETURNING id").Scan(&next); err != nil {
			t.Fatal(err)
		}
		if next != 3 {
			t.Fatalf("%s sequence restarted: %d", table, next)
		}
		var existing string
		if err := tx.QueryRow(t.Context(), "SELECT name FROM "+table+" WHERE id=1").Scan(&existing); err != nil || existing != "existing" {
			t.Fatalf("existing data: %q %v", existing, err)
		}
	}
}

func TestWidenCoreIDsPostgresDownGuards(t *testing.T) {
	for _, table := range coreIDParents {
		for _, kind := range []string{"high row", "low row", "high sequence", "low sequence"} {
			t.Run(table+"/"+kind, func(t *testing.T) {
				tx, schema := coreIDFixture(t)
				migrationExec(t, tx, adminMigrationSQL(t, widenCoreIDsMigrationName, schema, false))
				switch kind {
				case "high row":
					migrationExec(t, tx, "INSERT INTO "+table+"(id) VALUES(3000000000)")
				case "low row":
					migrationExec(t, tx, "INSERT INTO "+table+"(id) VALUES(-3000000000)")
				case "high sequence":
					migrationExec(t, tx, "SELECT setval(pg_get_serial_sequence('"+table+"','id'),3000000000,false)")
				case "low sequence":
					migrationExec(t, tx, "ALTER SEQUENCE "+table+"_id_seq MINVALUE -4000000000; SELECT setval(pg_get_serial_sequence('"+table+"','id'),-3000000000,false)")
				}
				savepoint, err := tx.Begin(t.Context())
				if err != nil {
					t.Fatal(err)
				}
				_, err = savepoint.Exec(t.Context(), adminMigrationSQL(t, widenCoreIDsMigrationName, schema, true))
				_ = savepoint.Rollback(t.Context())
				if err == nil || !strings.Contains(err.Error(), "widen_core_ids_to_bigint down: "+schema+"."+table) {
					t.Fatalf("expected named guard for %s: %v", table, err)
				}
				assertCoreIDTypes(t, tx, schema, "bigint")
			})
		}
	}
}

func TestWidenCoreIDsPostgresRequiresIdentityPredecessor(t *testing.T) {
	tx, schema := coreIDFixture(t)
	migrationExec(t, tx, "ALTER TABLE users ALTER COLUMN id DROP IDENTITY")
	requireMigrationSQLState(t, tx, adminMigrationSQL(t, widenCoreIDsMigrationName, schema, false), "P0001")
	var typ string
	if err := tx.QueryRow(t.Context(), "SELECT atttypid::regtype::text FROM pg_attribute WHERE attrelid='media_folders'::regclass AND attname='id'").Scan(&typ); err != nil || typ != "integer" {
		t.Fatalf("partial migration: %s %v", typ, err)
	}
}

func TestWidenCoreIDsPostgresUnusedSequences(t *testing.T) {
	tx, schema := coreIDFixture(t)
	for _, table := range coreIDParents {
		migrationExec(t, tx, "DELETE FROM "+table+"_children; DELETE FROM "+table+"; SELECT setval(pg_get_serial_sequence('"+table+"','id'),1,false)")
	}
	migrationExec(t, tx, adminMigrationSQL(t, widenCoreIDsMigrationName, schema, false))
	migrationExec(t, tx, adminMigrationSQL(t, widenCoreIDsMigrationName, schema, true))
	for _, table := range coreIDParents {
		var next int64
		if err := tx.QueryRow(t.Context(), "INSERT INTO "+table+" DEFAULT VALUES RETURNING id").Scan(&next); err != nil || next != 1 {
			t.Fatalf("%s unused sequence next=%d: %v", table, next, err)
		}
	}
}

func TestWidenCoreIDsPostgresCustomSequenceOptions(t *testing.T) {
	tx, schema := coreIDFixture(t)
	migrationExec(t, tx, "ALTER SEQUENCE users_id_seq INCREMENT BY 7 MINVALUE -100 MAXVALUE 1000000 START WITH 8 CACHE 3 CYCLE; SELECT setval('users_id_seq',99,false)")
	migrationExec(t, tx, adminMigrationSQL(t, widenCoreIDsMigrationName, schema, false))
	migrationExec(t, tx, adminMigrationSQL(t, widenCoreIDsMigrationName, schema, true))
	var increment, minimum, maximum, start, cache, position int64
	var cycle, called bool
	if err := tx.QueryRow(t.Context(), `SELECT seqincrement,seqmin,seqmax,seqstart,seqcache,seqcycle,last_value,is_called FROM pg_sequence CROSS JOIN users_id_seq WHERE seqrelid='users_id_seq'::regclass`).Scan(&increment, &minimum, &maximum, &start, &cache, &cycle, &position, &called); err != nil {
		t.Fatal(err)
	}
	if increment != 7 || minimum != -100 || maximum != 1000000 || start != 8 || cache != 3 || !cycle || position != 99 || called {
		t.Fatalf("custom sequence options changed: %d %d %d %d %d %t %d %t", increment, minimum, maximum, start, cache, cycle, position, called)
	}
}

func TestWidenCoreIDsPostgresGeneratedIDsCrossInt4Boundary(t *testing.T) {
	tx, schema := coreIDFixture(t)
	migrationExec(t, tx, adminMigrationSQL(t, widenCoreIDsMigrationName, schema, false))
	for _, table := range coreIDParents {
		migrationExec(t, tx, "SELECT setval(pg_get_serial_sequence('"+table+"','id'),2147483647,true)")
		var id int64
		if err := tx.QueryRow(t.Context(), "INSERT INTO "+table+" DEFAULT VALUES RETURNING id").Scan(&id); err != nil || id != 2147483648 {
			t.Fatalf("%s generated id=%d: %v", table, id, err)
		}
	}
}
