// Generates the web-side v2 contract artifacts from the committed OpenAPI
// document (contracts/api/v2/openapi.json):
//
//   src/api/v2/schema.ts      the openapi-typescript `paths`/`components`/
//                             `operations` types
//   src/api/v2/operations.ts  the runtime "METHOD /path" -> operationId map
//                             the request boundary uses to label errors
//
// Both files are formatted with the repository prettier config so
// `make verify-apiv2-web-types` can byte-compare a fresh generation against
// the committed pair. Usage: node scripts/generate-apiv2.mjs [--out-dir DIR]
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import prettier from "prettier";

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const specPath = path.resolve(webRoot, "../contracts/api/v2/openapi.json");
const defaultOutDir = path.join(webRoot, "src/api/v2");

function parseArgs(argv) {
  let outDir = defaultOutDir;
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--out-dir") {
      outDir = path.resolve(argv[i + 1] ?? "");
      i += 1;
    } else {
      throw new Error(`unknown argument: ${argv[i]}`);
    }
  }
  return { outDir };
}

const HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"];

function operationsModule(spec) {
  const entries = [];
  for (const [route, item] of Object.entries(spec.paths ?? {})) {
    for (const method of HTTP_METHODS) {
      const op = item[method];
      if (!op?.operationId) continue;
      entries.push([`${method.toUpperCase()} ${route}`, op.operationId]);
    }
  }
  entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const lines = entries.map(([key, id]) => `  ${JSON.stringify(key)}: ${JSON.stringify(id)},`);
  return [
    "/**",
    " * This file was auto-generated by scripts/generate-apiv2.mjs from",
    " * contracts/api/v2/openapi.json. Do not make direct changes to the file.",
    " */",
    "",
    "/** Operation ids keyed by `METHOD /path`, as the committed v2 OpenAPI document lists them. */",
    "export const v2Operations = {",
    ...lines,
    "} as const;",
    "",
  ].join("\n");
}

async function format(filePath, source) {
  const config = (await prettier.resolveConfig(filePath, { editorconfig: true })) ?? {};
  return prettier.format(source, { ...config, filepath: filePath });
}

async function main() {
  const { outDir } = parseArgs(process.argv.slice(2));
  const spec = JSON.parse(await readFile(specPath, "utf8"));
  const ast = await openapiTS(spec, { alphabetize: true });
  await mkdir(outDir, { recursive: true });
  const outputs = [
    ["schema.ts", astToString(ast)],
    ["operations.ts", operationsModule(spec)],
  ];
  for (const [name, source] of outputs) {
    const target = path.join(outDir, name);
    // Format against the canonical location so the prettier config resolves
    // the same way whether the output lands in src/api/v2 or a temp dir.
    await writeFile(target, await format(path.join(defaultOutDir, name), source));
  }
}

await main();
