package scenariocatalog

import (
	"bufio"
	"bytes"
	"fmt"
	"io/fs"
	"reflect"
	"sort"
	"strings"

	apiv2 "github.com/Silo-Server/silo-server/contracts/api/v2"
)

// OfflineRouteSet is the committed answer to "which rows does the API
// listener register under the scenario executor's offline wiring?". The
// executor needs it to decide whether a public scenario can run without a
// database, and api.NewRouter hands out a sealed http.Handler that nothing
// outside a test in internal/api can walk. So TestOfflineRouteSet there
// builds the wiring through the unexported constructor, walks it, and pins
// the result in contracts/api/v2/offline-routes.txt; the executor loads
// that file and refuses it when its Wiring line no longer describes the
// Dependencies the executor itself builds.
type OfflineRouteSet struct {
	// Wiring names the api.Dependencies fields the offline router was built
	// with (every non-zero field, sorted). Every registration condition the
	// route inventory records is a presence test on one of these, so the
	// names pin the registration outcome exactly.
	Wiring []string
	// Routes holds "METHOD path" keys in the route inventory's spelling.
	Routes map[string]bool
}

// Has reports whether the offline router registered the row.
func (s *OfflineRouteSet) Has(method, path string) bool {
	return s.Routes[method+" "+path]
}

// offlineRoutesHeader opens the committed file. Decode skips comment lines,
// so the text can change without touching the parser.
const offlineRoutesHeader = `# Routes the API listener registers under the scenario executor's offline
# wiring. The "wiring:" line names the api.Dependencies fields that were set
# (the executor checks it against its own construction); each other line is
# one "METHOD path" row in the route inventory's spelling, sorted.
#
# Generated by TestOfflineRouteSet (internal/api) from the real router.
# Regenerate with make offline-routes; make verify-offline-routes fails when
# this file is stale. Do not edit by hand.
`

const wiringPrefix = "wiring:"

// WiringFields lists the names of the non-zero fields of a struct value,
// sorted. It is how both the generator and the executor describe an
// api.Dependencies value without either importing the other.
func WiringFields(v any) []string {
	rv := reflect.Indirect(reflect.ValueOf(v))
	if rv.Kind() != reflect.Struct {
		panic(fmt.Sprintf("scenariocatalog: WiringFields wants a struct, got %T", v))
	}
	var names []string
	for i := 0; i < rv.NumField(); i++ {
		if !rv.Field(i).IsZero() {
			names = append(names, rv.Type().Field(i).Name)
		}
	}
	sort.Strings(names)
	return names
}

// EncodeOfflineRoutes renders the committed file: the header, the wiring
// line, then the routes sorted and deduplicated, one per line.
func EncodeOfflineRoutes(wiring, routes []string) []byte {
	var b bytes.Buffer
	b.WriteString(offlineRoutesHeader)
	b.WriteString(wiringPrefix + " " + strings.Join(wiring, " ") + "\n")
	sorted := append([]string(nil), routes...)
	sort.Strings(sorted)
	for i, r := range sorted {
		if i > 0 && r == sorted[i-1] {
			continue
		}
		b.WriteString(r + "\n")
	}
	return b.Bytes()
}

// DecodeOfflineRoutes parses the committed file. A route line that is not
// exactly an upper-case method and a rooted path, a missing or repeated
// wiring line, and an empty route list are errors rather than silently
// weaker sets: a file that pins nothing would turn every offline decision
// into a skip.
func DecodeOfflineRoutes(data []byte) (*OfflineRouteSet, error) {
	set := &OfflineRouteSet{Routes: map[string]bool{}}
	sc := bufio.NewScanner(bytes.NewReader(data))
	for n := 1; sc.Scan(); n++ {
		line := strings.TrimSpace(sc.Text())
		switch {
		case line == "" || strings.HasPrefix(line, "#"):
			continue
		case strings.HasPrefix(line, wiringPrefix):
			if set.Wiring != nil {
				return nil, fmt.Errorf("offline routes: line %d: second wiring line", n)
			}
			set.Wiring = strings.Fields(strings.TrimPrefix(line, wiringPrefix))
			if len(set.Wiring) == 0 {
				return nil, fmt.Errorf("offline routes: line %d: empty wiring line", n)
			}
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 || fields[0] != strings.ToUpper(fields[0]) || !strings.HasPrefix(fields[1], "/") {
			return nil, fmt.Errorf("offline routes: line %d: want \"METHOD /path\", got %q", n, line)
		}
		set.Routes[fields[0]+" "+fields[1]] = true
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("offline routes: %w", err)
	}
	if set.Wiring == nil {
		return nil, fmt.Errorf("offline routes: no %q line", wiringPrefix)
	}
	if len(set.Routes) == 0 {
		return nil, fmt.Errorf("offline routes: no routes")
	}
	return set, nil
}

// LoadOfflineRoutes reads the committed offline route set from the embedded
// contract artifacts.
func LoadOfflineRoutes() (*OfflineRouteSet, error) {
	raw, err := fs.ReadFile(apiv2.FS, apiv2.OfflineRoutesPath)
	if err != nil {
		return nil, fmt.Errorf("scenariocatalog: read %s: %w", apiv2.OfflineRoutesPath, err)
	}
	set, err := DecodeOfflineRoutes(raw)
	if err != nil {
		return nil, fmt.Errorf("scenariocatalog: %s: %w", apiv2.OfflineRoutesPath, err)
	}
	return set, nil
}
