-- +goose Up
-- +goose StatementBegin
-- Convert the 32 legacy id generators to BY DEFAULT identity. Explicit ids remain
-- accepted. Revision defaults use shared sequences and are deliberately excluded.
-- Stop every API/integrated replica before applying this maintenance migration.
-- Each table is locked before reading its sequence; all conversions commit together.
-- Preserve sequence position (including is_called), options, and name. Existing
-- rows and constraints are unchanged; explicit ids do not advance the sequence.
-- Dependent objects that prevent DROP SEQUENCE make the transaction fail intact.
DO $$
DECLARE
    target text;
    seq text;
    last_val bigint;
    called boolean;
    identity_kind "char";
    options record;
    targets text[] := ARRAY[
        'abs_sessions',
        'activity_log',
        'api_keys',
        'artwork_revision_gc_candidates',
        'autoscan_events',
        'autoscan_webhook_deliveries',
        'catalog_search_index_events',
        'download_artifact_orphans',
        'downloaded_subtitles',
        'invite_codes',
        'marker_edit_audit',
        'media_files',
        'media_folder_paths',
        'media_folders',
        'media_identity_overrides',
        'metadata_image_cache_jobs',
        'metadata_translation_jobs',
        'playback_route_events',
        'plugin_auth_bindings',
        'plugin_auth_identities',
        'plugin_capabilities',
        'plugin_installations',
        'plugin_repositories',
        'plugin_runtime_configs',
        'plugin_task_bindings',
        'stream_nodes',
        'subtitle_ai_jobs',
        'task_executions',
        'task_triggers',
        'user_setting_migration_rejects',
        'user_setting_values',
        'users'
    ];
BEGIN
    FOREACH target IN ARRAY targets LOOP
        SELECT a.attidentity INTO identity_kind
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
        WHERE c.relname = target AND a.attname = 'id' AND NOT a.attisdropped;

        IF identity_kind IS NULL THEN
            RAISE EXCEPTION 'serial-to-identity: public.%.id does not exist', target;
        END IF;
        IF identity_kind <> '' THEN
            CONTINUE;
        END IF;

        seq := pg_get_serial_sequence('public.' || quote_ident(target), 'id');
        IF seq IS NULL THEN
            RAISE EXCEPTION 'serial-to-identity: public.%.id owns no sequence', target;
        END IF;

        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id DROP DEFAULT', target);
        EXECUTE format('SELECT last_value, is_called FROM %s', seq) INTO last_val, called;
        SELECT seqstart, seqincrement, seqmin, seqmax, seqcache, seqcycle
        INTO STRICT options FROM pg_sequence WHERE seqrelid = seq::regclass;
        EXECUTE format('DROP SEQUENCE %s', seq);
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME %s START WITH %s INCREMENT BY %s MINVALUE %s MAXVALUE %s CACHE %s %s)',
                       target, seq, options.seqstart, options.seqincrement, options.seqmin,
                       options.seqmax, options.seqcache, CASE WHEN options.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END);
        PERFORM setval(pg_get_serial_sequence('public.' || quote_ident(target), 'id'), last_val, called);
    END LOOP;
END
$$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Restore serial defaults with the current sequence name, generation options,
-- and reserved position. DROP IDENTITY removes the owned sequence, so capture
-- its state under the table lock first. Use the column type for the new sequence.
DO $$
DECLARE
    target text;
    seq text;
    seq_name text;
    col_type text;
    last_val bigint;
    called boolean;
    identity_kind "char";
    options record;
    targets text[] := ARRAY[
        'abs_sessions',
        'activity_log',
        'api_keys',
        'artwork_revision_gc_candidates',
        'autoscan_events',
        'autoscan_webhook_deliveries',
        'catalog_search_index_events',
        'download_artifact_orphans',
        'downloaded_subtitles',
        'invite_codes',
        'marker_edit_audit',
        'media_files',
        'media_folder_paths',
        'media_folders',
        'media_identity_overrides',
        'metadata_image_cache_jobs',
        'metadata_translation_jobs',
        'playback_route_events',
        'plugin_auth_bindings',
        'plugin_auth_identities',
        'plugin_capabilities',
        'plugin_installations',
        'plugin_repositories',
        'plugin_runtime_configs',
        'plugin_task_bindings',
        'stream_nodes',
        'subtitle_ai_jobs',
        'task_executions',
        'task_triggers',
        'user_setting_migration_rejects',
        'user_setting_values',
        'users'
    ];
BEGIN
    FOREACH target IN ARRAY targets LOOP
        SELECT a.attidentity, format_type(a.atttypid, a.atttypmod)
        INTO identity_kind, col_type
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
        WHERE c.relname = target AND a.attname = 'id' AND NOT a.attisdropped;

        IF identity_kind IS NULL THEN
            RAISE EXCEPTION 'identity-to-serial: public.%.id does not exist', target;
        END IF;
        IF identity_kind = '' THEN
            CONTINUE;
        END IF;

        seq := pg_get_serial_sequence('public.' || quote_ident(target), 'id');
        SELECT c.relname INTO seq_name FROM pg_class c WHERE c.oid = seq::regclass;
        -- Lock before reading the position so a concurrent insert cannot advance the
        -- sequence between the read and DROP IDENTITY (the Up gets this lock from DROP DEFAULT).
        EXECUTE format('LOCK TABLE public.%I IN ACCESS EXCLUSIVE MODE', target);
        EXECUTE format('SELECT last_value, is_called FROM %s', seq) INTO last_val, called;
        SELECT seqstart, seqincrement, seqmin, seqmax, seqcache, seqcycle
        INTO STRICT options FROM pg_sequence WHERE seqrelid = seq::regclass;

        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id DROP IDENTITY', target);
        EXECUTE format('CREATE SEQUENCE public.%I AS %s START WITH %s INCREMENT BY %s MINVALUE %s MAXVALUE %s CACHE %s %s OWNED BY public.%I.id',
                       seq_name, col_type, options.seqstart, options.seqincrement, options.seqmin,
                       options.seqmax, options.seqcache, CASE WHEN options.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END, target);
        PERFORM setval(format('public.%I', seq_name)::regclass, last_val, called);
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT nextval(%L)',
                       target, format('public.%I', seq_name));
    END LOOP;
END
$$;
-- +goose StatementEnd
