-- +goose Up
-- Widen the three core parent IDs after the schema hygiene identity migration.
-- See docs/architecture/core-id-range.md for remaining references and limits.
-- Integer children deliberately retain their existing limits. This is schema
-- standardization; workflows writing those children still require int4 IDs.
--
-- Each ALTER rewrites the parent and its indexes and revalidates referencing
-- foreign keys. Referencing tables also take ACCESS EXCLUSIVE locks. Schedule
-- a maintenance window, allow space for table/index copies, and increase
-- SILO_MIGRATE_TIMEOUT for large catalogs. All changes share one transaction.
-- Identity sequences widen with their columns, retaining position/is_called.
-- +goose StatementBegin
DO $$
DECLARE
    target text;
BEGIN
    FOREACH target IN ARRAY ARRAY['media_folders', 'users', 'media_files'] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_attribute
            WHERE attrelid = format('public.%I', target)::regclass
              AND attname = 'id' AND attidentity = 'd'
        ) THEN
            RAISE EXCEPTION 'widen_core_ids_to_bigint: public.%.id must be GENERATED BY DEFAULT AS IDENTITY; apply the preceding schema hygiene migration first', target;
        END IF;
    END LOOP;
END
$$;
ALTER TABLE public.media_folders ALTER COLUMN id TYPE bigint;
ALTER TABLE public.users ALTER COLUMN id TYPE bigint;
ALTER TABLE public.media_files ALTER COLUMN id TYPE bigint;
-- +goose StatementEnd

-- +goose Down
-- Lock before inspecting rows so concurrent writers cannot pass the guard.
-- Sequence bounds are checked separately: deleted rows may leave an exhausted
-- sequence. A refusal rolls back the entire migration, including these locks.
-- +goose StatementBegin
LOCK TABLE public.media_folders, public.users, public.media_files IN ACCESS EXCLUSIVE MODE;
DO $$
DECLARE
    target text;
    min_id bigint;
    max_id bigint;
    seq_pos bigint;
BEGIN
    FOREACH target IN ARRAY ARRAY['media_folders', 'users', 'media_files'] LOOP
        EXECUTE format('SELECT min(id), max(id) FROM public.%I', target) INTO min_id, max_id;
        IF min_id < -2147483648 OR max_id > 2147483647 THEN
            RAISE EXCEPTION 'widen_core_ids_to_bigint down: public.%.id range [%, %] does not fit integer', target, min_id, max_id;
        END IF;
        EXECUTE format('SELECT last_value FROM %s', pg_get_serial_sequence('public.' || quote_ident(target), 'id')) INTO seq_pos;
        IF seq_pos < -2147483648 OR seq_pos > 2147483647 THEN
            RAISE EXCEPTION 'widen_core_ids_to_bigint down: public.% identity sequence position % does not fit integer', target, seq_pos;
        END IF;
    END LOOP;
END
$$;
ALTER TABLE public.media_files ALTER COLUMN id TYPE integer;
ALTER TABLE public.users ALTER COLUMN id TYPE integer;
ALTER TABLE public.media_folders ALTER COLUMN id TYPE integer;
-- +goose StatementEnd
