package s3client

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/http/httptrace"
	"sync"
	"time"

	"github.com/Silo-Server/silo-server/internal/telemetry"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/retry"
	"github.com/aws/smithy-go/middleware"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

const s3RoleLabel = "role"

var s3Retries = promauto.NewCounterVec(prometheus.CounterOpts{Name: "silo_s3_retries_total", Help: "S3 SDK retries after the initial attempt."}, []string{s3RoleLabel, "operation"})
var s3Bytes = promauto.NewCounterVec(prometheus.CounterOpts{Name: "silo_s3_body_bytes_total", Help: "S3 HTTP body bytes consumed by the transport or caller, including retries and error responses; excludes headers and protocol overhead."}, []string{s3RoleLabel, "direction"})
var s3BodyErrors = promauto.NewCounterVec(prometheus.CounterOpts{Name: "silo_s3_body_errors_total", Help: "S3 HTTP body read errors excluding EOF."}, []string{s3RoleLabel, "direction"})
var s3ConnectionWait = promauto.NewHistogramVec(prometheus.HistogramOpts{Name: "silo_s3_connection_wait_seconds", Help: "S3 HTTP connection acquisition including dial and TLS setup.", Buckets: []float64{.001, .01, .05, .1, .5, 1, 5, 30}}, []string{s3RoleLabel, "reused"})

func s3Operation(op string) string {
	switch op {
	case "GetObject", "PutObject", "HeadObject", "HeadBucket", "DeleteObject", "DeleteObjects", "ListObjectsV2", "PutBucketCors", "PutObjectAcl", "CreateMultipartUpload", "UploadPart", "CompleteMultipartUpload", "AbortMultipartUpload":
		return op
	default:
		return "other"
	}
}

func observeS3(role string) func(*middleware.Stack) error {
	return func(stack *middleware.Stack) error {
		// The stack ID is generated by the SDK, never a bucket, key or URL.
		op := s3Operation(stack.ID())
		return stack.Initialize.Add(middleware.InitializeMiddlewareFunc("SiloObserve", func(ctx context.Context, in middleware.InitializeInput, next middleware.InitializeHandler) (middleware.InitializeOutput, middleware.Metadata, error) {
			ctx, finish := telemetry.StartDependency(ctx, "s3", role, op)
			out, metadata, err := next.HandleInitialize(ctx, in)
			finish(err)
			if attempts, ok := retry.GetAttemptResults(metadata); ok && len(attempts.Results) > 1 {
				s3Retries.WithLabelValues(role, op).Add(float64(len(attempts.Results) - 1))
			}
			return out, metadata, err
		}), middleware.Before)
	}
}

// S3 streams stay streamed. Counting happens as bytes are read and never drains
// or buffers a body. Logical call latency ends at the SDK return (headers for
// GetObject), whereas byte totals continue until the caller closes the body.
type observedBody struct {
	io.ReadCloser
	bytes  prometheus.Counter
	errors prometheus.Counter
}

func (b *observedBody) Read(p []byte) (int, error) {
	n, err := b.ReadCloser.Read(p)
	b.bytes.Add(float64(n))
	if err != nil && !errors.Is(err, io.EOF) {
		b.errors.Inc()
	}
	return n, err
}

type observedHTTPClient struct {
	inner aws.HTTPClient
	role  string
}

func (c observedHTTPClient) Do(req *http.Request) (*http.Response, error) {
	var mu sync.Mutex
	var start time.Time
	ct := &httptrace.ClientTrace{
		GetConn: func(string) { mu.Lock(); start = time.Now(); mu.Unlock() },
		GotConn: func(info httptrace.GotConnInfo) {
			mu.Lock()
			began := start
			mu.Unlock()
			if began.IsZero() {
				return
			}
			reused := "false"
			if info.Reused {
				reused = "true"
			}
			s3ConnectionWait.WithLabelValues(c.role, reused).Observe(time.Since(began).Seconds())
		},
	}
	copy := req.Clone(httptrace.WithClientTrace(req.Context(), ct))
	if req.Body != nil {
		copy.Body = c.body(req.Body, "upload")
	}
	resp, err := c.inner.Do(copy)
	if resp != nil && resp.Body != nil {
		resp.Body = c.body(resp.Body, "download")
	}
	return resp, err
}
func (c observedHTTPClient) body(body io.ReadCloser, direction string) io.ReadCloser {
	return &observedBody{ReadCloser: body, bytes: s3Bytes.WithLabelValues(c.role, direction), errors: s3BodyErrors.WithLabelValues(c.role, direction)}
}
